jwt:
  key:
    key-location: yak-common.jks  # 去掉 `classpath:` 前缀
    alias: yakmall
    key-pass: yakmall123          # 密钥密码
    store-pass: yakmall123        # 存储密码

#  jwt:
#    location: classpath:yak-common.jks
#    alias: yakmall
#    password: yakmall123
#    tokenTTL: 30d
#  auth:
#    excludePaths: /api/public,/login

# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123