server:
  port: 8082
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
yak:
  springdoc:
    package: com.yakmall.user.controller
jwt:
  key:
    key-location: yak-common.jks  # 去掉 `classpath:` 前缀
    alias: yakmall
    key-pass: yakmall123          # 密钥密码
    store-pass: yakmall123        # 存储密码

