server:
  port: 8083
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
yak:
  springdoc:
    package: com.yakmall.cart.controller


#  datasource:
#    url: jdbc:mysql://${yak.db.host}:3306/yakmall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: ${yak.db.pw}

#
#mybatis-plus:
##  这里配置了mapper.xml文件的位置
#  mapper-locations: classpath*:/mapper/**/*.xml
#  configuration:
#    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#    map-underscore-to-camel-case: true # 新增关键配置（开启驼峰转换）
#  type-aliases-package: com.yakmall.domain.po
#  global-config:
#    db-config:
#      update-strategy: not_null
#      id-type: auto
#logging:
#  level:
#    com.yakmall: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
#  file:
#    path: "logs/${spring.application.name}"
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html      # 原生UI路径
#    tags-sorter: alpha          # 标签排序规则
#    operations-sorter: alpha     # 接口排序规则
#  api-docs:
#    path: /v3/api-docs          # OpenAPI描述文件路径
#  packages-to-scan: com.yakmall.cart.controller  # 扫描的Controller包路径
#  knife4j:
#    enable: true                # 启用Knife4j增强
#    setting:
#      language: zh-CN           # 中文界面
#      enable-swagger-model: true
#      enable-document-manage: true

# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123